version: '3'
services:
  myapp:
    image: bikrent-goapp:latest
    container_name: bikrent-goapp1
    ports:
      - "8080:80"  # Map port 8080 on your host to port 80 in the container
    environment:
      - DB_HOST=mydb
      - DB_PORT=3308
      - DB_USER=bikrent-goapp
      - DB_PASSWORD=Kotamedan3
      - DB_NAME=bikrentgoapp
    networks:
      - mynetwork
    # Other configuration options for your application

  mydb:
    image: mysql
    container_name: mysqldocker1
    environment:
      MYSQL_ROOT_PASSWORD: Kotamedan3
      MYSQL_DATABASE: bikrentgoapp
      MYSQL_USER: bikrent-goapp
      MYSQL_PASSWORD: Kotamedan3
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork
    # Other configuration options for your database

networks:
  mynetwork:

volumes:
  db-data:

